# Generated by Django 2.2.12 on 2022-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyorder',
            name='email',
            field=models.EmailField(default='123', max_length=254, verbose_name='電子信箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyorder',
            name='phone',
            field=models.CharField(default='0900000000', max_length=10, verbose_name='手機'),
            preserve_default=False,
        ),
    ]
