# Generated by Django 2.2.12 on 2022-03-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_size', models.CharField(max_length=10, verbose_name='商品尺寸')),
                ('item_num', models.IntegerField(verbose_name='訂購數量')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='加入日期')),
            ],
            options={
                'verbose_name_plural': '購物車',
                'db_table': 'users_cart_items',
            },
        ),
        migrations.CreateModel(
            name='FavorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='收藏日期')),
                ('active', models.BooleanField(default=1, verbose_name='是否使用')),
            ],
            options={
                'verbose_name_plural': '收藏清單',
                'db_table': 'users_favor_items',
            },
        ),
        migrations.CreateModel(
            name='ItemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='名稱')),
                ('item_num', models.CharField(max_length=6, verbose_name='編號')),
                ('price', models.IntegerField(verbose_name='價格')),
                ('pic', models.ImageField(upload_to='item_pic/', verbose_name='圖片')),
                ('item_class', models.CharField(choices=[('外套', '外套'), ('帽T', '帽T'), ('長袖', '長袖'), ('短袖', '短袖'), ('背心', '背心'), ('長褲', '長褲'), ('短褲', '短褲'), ('帽子', '帽子'), ('襪子', '襪子'), ('背包', '背包')], max_length=6, verbose_name='類別')),
                ('item_amount', models.IntegerField(verbose_name='庫存量')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('active', models.BooleanField(default=1, verbose_name='是否使用')),
                ('cart', models.ManyToManyField(related_name='user_cart', through='items.CartItems', to='users.UserProfile')),
                ('favor', models.ManyToManyField(related_name='user_favor', through='items.FavorItem', to='users.UserProfile')),
            ],
            options={
                'verbose_name_plural': '商品資訊',
                'db_table': 'items_item_profile',
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_score', models.IntegerField(verbose_name='評分')),
                ('upload_time', models.DateField(auto_now=True, verbose_name='評分日期')),
                ('active', models.BooleanField(default=1, verbose_name='是否使用')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemProfile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'verbose_name_plural': '評分清單',
                'db_table': 'users_score_items',
            },
        ),
        migrations.AddField(
            model_name='itemprofile',
            name='score',
            field=models.ManyToManyField(related_name='user_score', through='items.ScoreItem', to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='itemprofile',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.VendorProfile'),
        ),
        migrations.AddField(
            model_name='favoritem',
            name='itemname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemProfile'),
        ),
        migrations.AddField(
            model_name='favoritem',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemProfile'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
